name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - 'byoc/image-push/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'byoc/image-push/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./byoc/image-push
          file: ./byoc/image-push/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USER }}/byoc-image-push:${{ github.sha }}